name: Tagged Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-tagged-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: get_tag
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 18.x
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build Web Assets
        working-directory: ./web
        run: |
          yarn install
          yarn build
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: Snowy Shops - ${{ steps.get_tag.outputs.VERSION_TAG }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
        id: auto_release
      - name: Upload Web Build
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.auto_release.outputs.upload_url }}
          asset_path: ./web/build
          asset_name: web-build
          asset_content_type: application/zip
          