name: Tagged Release
on:
  push:
    tags:
      - "v*"
jobs:
  create-tagged-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: get_tag
      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v4'
        with:
          node-version: 18.x
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            **/.yarn/cache
            **/.yarn/unplugged
            **/.yarn/build-state.yml
            **/.yarn/install-state.gz
            **/.pnp.*
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Yarn
        run: npm install -g yarn
      - name: Build Web Assets
        working-directory: ./web
        run: |
          yarn install --frozen-lockfile
          yarn build
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Snowy Shops - ${{ steps.get_tag.outputs.VERSION_TAG }}
          draft: false
          prerelease: false
          generate_release_notes: true
        id: release
      - name: Upload Web Build
        uses: actions/upload-release-asset@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: ./web/build
          asset_name: web-build
          asset_content_type: application/zip
          